### ISSUE TITLE
nox-show-doc not work when "WenQuanYi Micro Hei Mono" not available

### ISSUE THREAD

**Issue by hzzhang** [manateelazycat/nox#1]
If "WenQuanYi Micro Hei Mono" font is not available, `nox-show-doc` will produce the following error message:
```
error in process filter: set-face-attribute: Font not available: #<font-spec nil nil WenQuanYi\ Micro\ Hei\ Mono-14 nil nil nil nil nil nil nil nil nil ((:name . "WenQuanYi Micro Hei Mono-14") (:user-spec . "WenQuanYi Micro Hei Mono-14"))>
```

Is it possible to make `nox-show-doc` following the existing font configuration, or make the font configurable?

**Comment by hzzhang** [comment]
Just notice `nox-doc-tooltip-font` was added. After setting it to a proper font, my issue was solved.

**Comment by manateelazycat** [comment]
Thanks for report, see also https://github.com/manateelazycat/nox/commit/a55c65ef1ed46553268812f5cd48381d5b049bdf

**Comment by hzzhang** [comment]
That is pretty cool! I even do not need to explicitly set the tooltip face. Thanks for the quick fix and improvement!
