### ISSUE TITLE
Is it possible to provide guide on how to use nox with Doom and Tramp?

### ISSUE THREAD

**Issue by whjiang** [manateelazycat/nox#10]
Currently, I am using lsp+ccls in Doom Emacs. However, it can't work under TRAMP. 

I am quite interested in this project. But, I don't know how to make it work with Doom and TRAMP. Can you provide some guide on this?

**Comment by manateelazycat** [comment]
Tramp is very slow protocol, completion can't work as your expect even tramp works.
