### ISSUE TITLE
error in process filter: set-face-attribute: Font not available

### ISSUE THREAD

**Issue by pigmej** [manateelazycat/nox#13]
I'm getting font error when doing `nox-show-doc`.

```
error in process filter: Font not available: #<font-spec nil nil Roboto\ Mono-10-14 nil nil nil nil nil nil nil nil nil ((:name . "Roboto Mono-10-14") (:user-spec . "Roboto Mono-10-14"))>
```

**Comment by manateelazycat** [comment]
What's output of your ```(frame-parameter nil 'font-parameter)``` ?

**Comment by manateelazycat** [comment]
@tumashu posframe 有只设置字体大小，但不设置字体的接口吗？

**Comment by tumashu** [comment]
暂时没有

**Comment by pigmej** [comment]
@manateelazycat the output is `Roboto Mono-10`

**Comment by jkunlin** [comment]
I have the same issue.

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/nox/commit/cc8d8bd019e958a09b3a1007874030e23d0356c0 has fix this issue.

Default, Nox not set posframe font, if font of posframe is too small to you, you can customize option nox-doc-tooltip-font, it need follow format ```fontname-fontsize```.
