### ISSUE TITLE
[jsonrpc] Server exited with status 126

### ISSUE THREAD

**Issue by ghost** [manateelazycat/nox#14]
M-x nox时出错，Python模式下。

*NOX Stderr*
```
emacs: /home/evanmeek/.emacs.d/var/nox/mspyls/Microsoft.Python.LanguageServer: 可执行文件格式错误

Process NOX (Code/python-mode) stderr finished
```

*NOX output*

empty

*NOX events*

`
internal Sat Apr 18 10:01:32 2020:
(:message "Connection state changed" :change "exited abnormally with code 126\n")

----------b---y---e---b---y---e----------
`

我用的mypyls

**Comment by manateelazycat** [comment]
仔细看readme，注意mspyls的路径和可执行权限

**Comment by ghost** [comment]
mspyls的路径不可以自定么？可执行文件权限现在已经给了。我现在将mspyls的路径改为默认的了，但是错误仍然是jsonrpc给的126。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Andy Stewart"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月18日(星期六) 上午10:55
收件人:&nbsp;"manateelazycat/nox"<nox@noreply.github.com&gt;;
抄送:&nbsp;"Evan"<2864011679@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [manateelazycat/nox] [jsonrpc] Server exited with status 126 (#14)





 
仔细看readme，注意mspyls的路径和可执行权限

**Comment by manateelazycat** [comment]
> mspyls的路径不可以自定么？可执行文件权限现在已经给了。我现在将mspyls的路径改为默认的了，但是错误仍然是jsonrpc给的126。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"Andy Stewart"<notifications@github.com&gt;; 发送时间:&nbsp;2020年4月18日(星期六) 上午10:55 收件人:&nbsp;"manateelazycat/nox"<nox@noreply.github.com&gt;; 抄送:&nbsp;"Evan"<2864011679@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [manateelazycat/nox] [jsonrpc] Server exited with status 126 (#14) 仔细看readme，注意mspyls的路径和可执行权限 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

自定义会增加初始使用门槛，具体什么路径不重要。

你的错误看着像架构的问题，你确定你下载的mspyls和你的操作系统是匹配的吗？（比如Mac的给Linux用）
或者你的CPU是32位的，但是可执行文件是64位的？

**Comment by ghost** [comment]
感谢勇哥这么迅速的回复，我下载的mypyls是通过(nox-print-mspyls-download-url)获取的，我的机器是64位的。我想是不是jsonrpc的问题。。我是要load仓库中的jsonrpc么？如果是jsongrpc的问题，我要如何获取错误帮助呢？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Andy Stewart"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月18日(星期六) 中午11:05
收件人:&nbsp;"manateelazycat/nox"<nox@noreply.github.com&gt;;
抄送:&nbsp;"Evan"<2864011679@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [manateelazycat/nox] [jsonrpc] Server exited with status 126 (#14)





  
mspyls的路径不可以自定么？可执行文件权限现在已经给了。我现在将mspyls的路径改为默认的了，但是错误仍然是jsonrpc给的126。
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"Andy Stewart"<notifications@github.com&gt;; 发送时间:&nbsp;2020年4月18日(星期六) 上午10:55 收件人:&nbsp;"manateelazycat/nox"<nox@noreply.github.com&gt;; 抄送:&nbsp;"Evan"<2864011679@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [manateelazycat/nox] [jsonrpc] Server exited with status 126 (#14) 仔细看readme，注意mspyls的路径和可执行权限 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
自定义会增加初始使用门槛，具体什么路径不重要。
 
你的错误看着像架构的问题，你确定你下载的mspyls和你的操作系统是匹配的吗？（比如Mac的给Linux用）
 或者你的CPU是32位的，但是可执行文件是64位的？

**Comment by ghost** [comment]
刚刚看了看下载的链接:"https://pvsc.blob.core.windows.net/python-language-server-stable/Python-Language-Server-linux-x64.0.5.45.nupkg"可以确定是Linux版本的了.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Andy Stewart"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月18日(星期六) 中午11:05
收件人:&nbsp;"manateelazycat/nox"<nox@noreply.github.com&gt;;
抄送:&nbsp;"Evan"<2864011679@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [manateelazycat/nox] [jsonrpc] Server exited with status 126 (#14)





  
mspyls的路径不可以自定么？可执行文件权限现在已经给了。我现在将mspyls的路径改为默认的了，但是错误仍然是jsonrpc给的126。
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"Andy Stewart"<notifications@github.com&gt;; 发送时间:&nbsp;2020年4月18日(星期六) 上午10:55 收件人:&nbsp;"manateelazycat/nox"<nox@noreply.github.com&gt;; 抄送:&nbsp;"Evan"<2864011679@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [manateelazycat/nox] [jsonrpc] Server exited with status 126 (#14) 仔细看readme，注意mspyls的路径和可执行权限 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
自定义会增加初始使用门槛，具体什么路径不重要。
 
你的错误看着像架构的问题，你确定你下载的mspyls和你的操作系统是匹配的吗？（比如Mac的给Linux用）
 或者你的CPU是32位的，但是可执行文件是64位的？
