### ISSUE TITLE
Doc pertinent options are obsolete

### ISSUE THREAD

**Issue by wanghaiqiangk** [manateelazycat/nox#20]
In the README page, some doc or tooltip related customizations are introduced. But they are banished from the source code right? What I want to ask is that can I make the doc persistent and highlight the parameter. This behaviour can be compared to eldoc except eldoc shows information in the echo area.

And I'm using nox in C/C++. I don't know how the doc is displayed for other programming languages.

**Comment by manateelazycat** [comment]
I have remove unused options from readme, thanks for report.

You can always show doc with command nox-show-doc.
