### ISSUE TITLE
how does nox read ccls project-specific initialization

### ISSUE THREAD

**Issue by wanghaiqiangk** [manateelazycat/nox#21]
Hello, yet another question.

ccls can be configured via `--init` option to set cache directory, compilation database, and so on. This is entailed to working on a project, especially if the compilation database is resided in non-standard location.

When I use nox with minimal customization, nox doesn't recognize those options values automatically. Then I see the `nox-workspace-configuration` variable which seems to be a workaround to tackle this problem. However, I don't know the syntax and the way to give ccls's init option value, even though I have seen the examples for python's and go's lsp server programs.

Can you illustrate by giving a code piece to clarify how to do that?

**Comment by manateelazycat** [comment]
Please search 

```
(cl-defmethod nox-initialization-options ((server nox-mspyls))
  "Pass dataPaths parameter require by intelephense."
  `(:interpreter
    (:properties
     (:InterpreterPath ,nox-python-path))
    :searchPaths ,nox-mspyls-search-paths
    :asyncStartup t
    :analysisUpdates t
    :logLevel "Error"
    :typeDefinitionProvider ,(concat nox-python-server-dir "Typeshed")))
```

And search ```nox--python-contact```

I think you can find way to customize ccls.
