### ISSUE TITLE
How to ignore the specified mode? like protobuf-mode

### ISSUE THREAD

**Issue by aggronmagi** [manateelazycat/nox#24]
An error message will be displayed every time when I open a protobuf file. 
How to ignore the specified mode?

"[nox] Couldn't guess for `(protobuf-mode)'!"

**Comment by manateelazycat** [comment]
please read README file, nox only enable by you setting

please check your config

**Comment by aggronmagi** [comment]
thank you. 
I remove 'c-mode-common-hook from default config. then it does not prompt any error messages.
