### ISSUE TITLE
 Cannot open load file, No such file or directory, jsonrpc

### ISSUE THREAD

**Issue by ghost** [manateelazycat/nox#3]
请问这是依赖哪个包

**Comment by LambdaRan** [comment]
我是直接在emacs仓库copy了一个，加到自己的load-path中。
https://github.com/emacs-mirror/emacs/blob/master/lisp/jsonrpc.el

**Comment by ghost** [comment]
> 我是直接在emacs仓库copy了一个，加到自己的load-path中。
> https://github.com/emacs-mirror/emacs/blob/master/lisp/jsonrpc.el

解决了，谢谢你，我就是找到了json-rpc.el但是没有找到jsonrpc.el

**Comment by manateelazycat** [comment]
I have add jsonrpc.el in repo, thanks for report! ;)
