### ISSUE TITLE
Support for imenu

### ISSUE THREAD

**Issue by hek14** [manateelazycat/nox#4]
From my personal viewpoint, the Emacs imenu gives me a good overview of the whole project, 
do you have any plan to add imenu integration?

**Comment by manateelazycat** [comment]
No, imenu will slow down speed.

Please use lsp-mode or eglot if you really like imenu.

**Comment by hek14** [comment]
Thanks for you reply! I finally chose to continue using nox and I implemented a simple imenu-create-index-function to integrate imenu.
