### ISSUE TITLE
Completion support

### ISSUE THREAD

**Issue by VojtechStep** [manateelazycat/nox#9]
The client declares snippet support in the default capabilities object, but I could't find any mention of snippets anywhere in the rest of the code, nor have I managed to get yasnippets working with this package.

If there is no support for snippets, the capability probably should be reported as unavailable, because it just pollutes completions with `$n` variables.

**Comment by manateelazycat** [comment]
This package not support snippet for performance, if you want snippet, please use lsp-mode or eglot.
